# Generated by Django 5.2.17 on 2026-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=254)),
                ('template', models.CharField(max_length=120)),
                ('provider_id', models.CharField(blank=True, max_length=160)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
